### PR TITLE
Add hard dollars

### PR DESCRIPTION
**Pull request by palewire**

### CODE REVIEW

**Review by dwillis — CHANGES_REQUESTED** [review]
I'm not sure the hard/soft distinction really makes sense anymore, tbh. Contributions to IE committees have to be disclosed as well, so disclosure isn't the issue. Committees that do IEs also can donate directly to candidates. It's essentially all hard money now.

**Comment by palewire** [comment]
Reflecting on this, here's where I come down. Feel free to disagree.

I'd make the case that professional usage alone should be our test for inclusion. Whether or not we agree with the recent usage of "hard dollars," the fact is that reporters are putting it in their stories, as documented by my proposed examples. 

If we applied an editorial test based on our own opinion about a word's fitness, we might have cut many more terms. For instance, I don't like the loose usage of the term Super PAC, but we include that in the dictionary.

**Comment by dwillis** [comment]
I get it, but "Super PAC" has an administrative definition. Hard money does not. I don't agree that we should be describing the bad uses of a term.

**Comment by palewire** [comment]
Alright, let's see if my sense of the hard-soft distinction over time matches your more experienced view. My general sense is that the Bipartisan Campaign Reform Act of 2002 and the Citizens United were watershed dividing lines that changed the parlance of our press.

||Before BCRA|After Citizens United|
|:---|:--|:---|
|hard money|funds contributed directly to campaigns that count against contribution limits|funds contributed directly to campaigns that count against contribution limits and, in contrast to soft money, can be spent directly on the activity of the official campaign|
|soft money|funds indirectly routed to campaigns via parties and other vehicles in a manner that evades contribution limits|independent expenditures made by outside groups that may benefit a campaign but cannot be coordinated with candidates or spent directly on the activity of the official campaign|

How'd I'd do, professor?

**Comment by dwillis** [comment]
Not bad; soft money was not routed to candidates but was given to national party committees and used by them for ads that were the equivalent of issue ads today. The real issue is that "guides" like [this one](https://www.investopedia.com/terms/s/softmoney.asp) completely misstate what is the law and what is happening. This guide is largely fiction except at the very broadest level.

Citizens United did not create independent expenditures; it broadened the scope of what kind of organizations could pay for them using particular sources (corporate treasury money, which previously could be given to parties as a soft money donation). But CU did not turn soft money into IEs. IEs have existed in law and in practice for decades, and are funded by disclosed donations with one exception, when 501c4s engage in what is known as electioneering communications. CU also did not change the definition of "hard money".

**Comment by palewire** [comment]
Do you think we need to tweak our existing soft money definition, then? https://moneyinpolitics.wtf/soft-money/

**Comment by dwillis** [comment]
Yeah, if we add a hard dollars, we probably should just to reflect that definition.

**Comment by palewire** [comment]
So here's what I have in the first proposal:

> funds donated directly to a [campaign](/campaign/) [committee](/committee/) that are publicly disclosed and subject to [contribution](/contribution/) limits; used by candidates and parties to pay for operating expenses like staff salaries, travel and events; distinguished from “soft” [independent expenditures](/independent-expenditure/) by [outside groups](/outside-group/) that cannot be put toward the day-to-day operation of a campaign

So am I correctly grokking that you'd be okay if we simply trimmed it to cut the IE language, like so:

> funds donated directly to a [campaign](/campaign/) [committee](/committee/) that are publicly disclosed and subject to [contribution](/contribution/) limits; used by candidates and parties to pay for operating expenses like staff salaries, travel and events

**Review by dwillis — APPROVED** [review]

**Pull request merged**
