### PR TITLE
Add electioneering communication

### PR DESCRIPTION
**Pull request by palewire**

### CODE REVIEW

**Review by dwillis — CHANGES_REQUESTED** [review]
We should specify that "electioneering communications" has a specific scope to federal elections and are only done by 501c4 nonprofits.

**Comment by palewire** [comment]
Doesn't the Montana story I linked show that this isn't just a federal term?

https://montanafreepress.org/2020/05/18/dark-money-group-found-in-violation-of-campaign-law/

**Comment by dwillis** [comment]
Ah, fair point. I guess it's worth clarifying that it's not just the disclosure requirements that vary depending on the level but also the definition of "electioneering communication" itself.

**Comment by palewire** [comment]
Gotcha. I took a run at that.

**Review by dwillis — APPROVED** [review]

**Pull request merged**
